-- =====================================================
-- AGGREGATION TABLES (for performance)
-- Pre-computed summaries generated by nightly job
-- =====================================================

-- =====================================================
-- DAILY SUMMARIES
-- =====================================================

CREATE TABLE IF NOT EXISTS public.daily_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  summary_date DATE NOT NULL,
  
  -- Aggregated recovery metrics
  avg_recovery_score DECIMAL(5,2),
  avg_hrv_rmssd DECIMAL(10,2),
  avg_resting_hr INTEGER,
  
  -- Aggregated sleep metrics
  total_sleep_minutes INTEGER,
  avg_sleep_quality_score DECIMAL(5,2),
  
  -- Aggregated workout metrics
  total_strain DECIMAL(5,2),
  total_calories INTEGER,
  total_workouts INTEGER,
  total_activity_minutes INTEGER,
  
  -- Data quality indicator
  data_completeness DECIMAL(3,2) CHECK (data_completeness >= 0 AND data_completeness <= 1),
  sources TEXT[], -- ['whoop', 'strava']
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, summary_date)
);

-- Enable RLS
ALTER TABLE public.daily_summaries ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Athletes view own daily summaries"
  ON public.daily_summaries FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Doctors view patient daily summaries"
  ON public.daily_summaries FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.doctor_patient_relationships
      WHERE doctor_id = auth.uid()
      AND patient_id = daily_summaries.user_id
      AND status = 'active'
    )
  );

-- Index for fast queries
CREATE INDEX idx_daily_summaries_user_date ON public.daily_summaries(user_id, summary_date DESC);

-- =====================================================
-- MONTHLY SUMMARIES
-- =====================================================

CREATE TABLE IF NOT EXISTS public.monthly_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  summary_month DATE NOT NULL, -- First day of month
  
  -- Aggregated metrics
  avg_recovery_score DECIMAL(5,2),
  avg_hrv_rmssd DECIMAL(10,2),
  avg_resting_hr INTEGER,
  total_sleep_hours DECIMAL(6,2),
  total_strain DECIMAL(5,2),
  total_calories INTEGER,
  total_workouts INTEGER,
  
  -- Trends (computed)
  recovery_trend TEXT CHECK (recovery_trend IN ('improving', 'stable', 'declining')),
  hrv_trend TEXT CHECK (hrv_trend IN ('improving', 'stable', 'declining')),
  
  -- Month-over-month comparison (percentage change)
  recovery_change_pct DECIMAL(5,2),
  hrv_change_pct DECIMAL(5,2),
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, summary_month)
);

-- Enable RLS
ALTER TABLE public.monthly_summaries ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Athletes view own monthly summaries"
  ON public.monthly_summaries FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Doctors view patient monthly summaries"
  ON public.monthly_summaries FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.doctor_patient_relationships
      WHERE doctor_id = auth.uid()
      AND patient_id = monthly_summaries.user_id
      AND status = 'active'
    )
  );

-- Index
CREATE INDEX idx_monthly_summaries_user_month ON public.monthly_summaries(user_id, summary_month DESC);
